CANONICAL_COLUMNS = [
    "Job Opportunity Name",
    "Employer Name",
    "Job Opportunity Stage",
    "Close Date",
    "Source",
    "Min Hours per Week",
    "Max Hours per Week",
    "Job Term",
    "Min Wage Normalized Hourly",
    "Max Wage Normalized Hourly",
    "Required Education",
    "Required Certifications & Licenses",
    "Category",
    "Vaccine Requirement",
    "Location",
    "Posting Date",
    "Original Min Compensation",
    "Original Max Compensation",
    "Compensation Period",
    "Compensation Currency",
    "Compensation Evidence",
    "Compensation Source",
    "Job Type Raw",
    "Job ID",
    "Job Description",
    "Responsibilities",
    "Qualifications",
    "Job Detail URL",
    "Source URL",
    "Date Scraped",
]
